/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniPlug */

#ifndef _Included_jni_JniPlug
#define _Included_jni_JniPlug
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniPlug
 * Method:    getNativeSring
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JniPlug_getNativeSring
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
